### ISSUE TITLE
botón "seguir"

### ISSUE THREAD

**Issue by manuelbarrosr** [ciudadanointeligente/estratega#116]
Comencé a subir el documento del Estratega OGP y luego de la primera parte -donde se ingresa problema, causa y posibles soluciones políticas- no tenía cómo volver al "dashboard" del proyecto para seguir con los siguientes pasos.

Para hacerlo tuve que volver a proyectos y luego entrar de nuevo a OGP.

Debería existir la manera de "seguir" el proceso una vez que se termina una etapa.

**Comment by jdgarrido** [comment]
related to #113
