### ISSUE TITLE
All stages - Text in general is not legible

### ISSUE THREAD

**Issue by lissteilor** [ciudadanointeligente/estratega#37]
![screen shot 2015-11-18 at 5 21 29 pm](https://cloud.githubusercontent.com/assets/13350590/11253213/eb55ed84-8e18-11e5-9227-8d5b87dbf585.png)
![screen shot 2015-11-18 at 5 21 40 pm](https://cloud.githubusercontent.com/assets/13350590/11253216/f02ba218-8e18-11e5-86a5-59df694380f0.png)
![screen shot 2015-11-18 at 5 22 53 pm](https://cloud.githubusercontent.com/assets/13350590/11253236/10322c6c-8e19-11e5-9805-aaa7e2515c94.png)

**Comment by marceloperez** [comment]
nisiquiera son img. tendríamos que aplicar grosor o más contraste si no los ves bien. la tipo delgada fue fijada por Cata en su propuesta inicial (Viz)

**Comment by marceloperez** [comment]
Se aumentó font-weight a 400 para el texto en general
