### ISSUE TITLE
Stage 2 - La ubicación del error no lo hace visible

### ISSUE THREAD

**Issue by lissteilor** [ciudadanointeligente/estratega#46]
El error sobre los objetivos no priorizados debería estar bajo la tabla de objetivos. Además, no es claro que debe priorizarse un objetivo para continuar.
![screen shot 2015-11-26 at 2 57 50 pm](https://cloud.githubusercontent.com/assets/13350590/11428801/6f43f52e-944e-11e5-9506-7177f1483580.png)

![screen shot 2015-11-26 at 3 01 24 pm](https://cloud.githubusercontent.com/assets/13350590/11428816/9a63269e-944e-11e5-8be2-436ac5a90e4a.png)

**Comment by marceloperez** [comment]
Poner ancla que suba hastra el mensaje
