### ISSUE TITLE
Update Ask model to be coherent with the methodology

### ISSUE THREAD

**Issue by maugsbur** [ciudadanointeligente/estratega#75]
Ask
- Description
- Belongs to one Interim Outcome
- Has many messages
- Belongs to one person in charge
- Has one Indicators

Message
- Description
- Belongs to one Ask
- Belongs to one Actor
- Delivered (boolean)

Activity
- Description
- Type of activity
- Time range
- Has many Actors

https://drive.google.com/a/votainteligente.cl/file/d/0B0yPPuIqAQBCVXFtZVA0RGh1cTg/view?usp=sharing

**Comment by jbci** [comment]
Asks may belong to interim outcome

**Comment by jbci** [comment]
Add Responsible
