### ISSUE TITLE
Stage 6 - Messages embedded in asks

### ISSUE THREAD

**Issue by maugsbur** [ciudadanointeligente/estratega#78]
<img width="1280" alt="captura de pantalla 2016-02-15 a las 6 11 27 p m" src="https://cloud.githubusercontent.com/assets/1598495/13157848/e18d00c4-d668-11e5-9c5b-16dcc8d687fa.png">

**Comment by jbci** [comment]
@marceloperez 
regarding new definitions of ask model as in #75,
columns activity and person in charge should not be in this table anymore because its a messages table.

may i straightly delete the columns or you prefer redesign it?
also which is the date to show in date column?

**Comment by marceloperez** [comment]
yes , remove with confidence
