### ISSUE TITLE
Peticiones - agregar actores

### ISSUE THREAD

**Issue by lavalebarahona** [ciudadanointeligente/estratega#94]
En esta parte no se explica cómo seleccionar más de un actor.  
![actores](https://cloud.githubusercontent.com/assets/11618128/13298368/430a8f5a-db15-11e5-9482-53fc73b9843d.png)

**Comment by jbci** [comment]
aclaremos este punto con @maugsbur, porque en los ultimos cambios para cada mensaje solo hay un actor como se define en el issue #84

**Comment by jbci** [comment]
@lavalebarahona 
hablado @maugsbur esta definido que las peticiones no tienen actores.
son los mensajes los que tienen un actor.
